aziontech/docs_en

image-processor/index.md
O título e 9 e 10 estão duplicados.
=> Correção de título de seção

intelligent-dns/index.md
Tradução iDNS pela traduzca
Adicionado documentação para o QTYPE CAA em inglês (já traduzido pela traduzca)
Adicionado novo formato de link para o github.
=> Intelligent dns (inglês)

changelog/index.md
=> changelog jun ds

edge-application/single-origin/index.md
Inclusion of a warning about the use of HMAC with Image Processor.
=> HMAC-IMS warning

edge-firewall/index.md
A formatação dos headers com links e sem links estava ficando muito diferente, então removi os links dos headers e adicionei um link See more.
=> Ajuste na formatação dos headers

edge-functions/index.md
edge-functions-en-grammatical-review
=> edge-functions-en-grammatical-review

changelog/index.md
=> changelog jul

changelog/index.md
=> Changelog sep

agreements/index.md, marketplace/isv-signup/index.md
=> Added link to marketplace agreement at agreements index

first-steps/index.md
Changes in the documentation and improvements
=> First steps_EN

real-time-events/index.md
Doc little changes + add Fields.
=> Real-Time Events Fields

edge-firewall/rules-engine/index.md
Doc improvement and corrections
=> Rules Engine - Edge Firewall_EN

edge-firewall/index.md
=> Edge Firewall - improvements

web-application-firewall/index.md
1.Corrected mistake caused by space between words >> the website shows everything:  1. How does it work? {#how does it work}
2. Also changed the interrogative  for an affirmative sentence  >> How it works
=> WebApplicationFirewall_En

edge-firewall/waf-rule-sets/index.md
improvements and steps correction
=> WAF Rule Set_improvements_EN

edge-firewall/edge-functions-instances/index.md
Steps corrections and improvements
=> Edge Firewall _Edge functions instances

marketplace/index.md, marketplace/isv-signup/index.md, marketplace/marketplace-seller-guide/index.md
=> Marketplace_EN corrections

edge-orchestrator/edge-node/index.md
=> edge node update

edge-firewall/access-permissions/index.md
Doc improvements and corrections
=> Access Permissions_ Edge Firewall

intelligent-dns/index.md
=> PMK - 459 Update Intelligent DNS Product Documentation

api/v3/intelligent-dns/index.md
=> PMK-461 Update Intelligent DNS API Documentation (DELETE endpoint) 

network-layer-protection/index.md
=> Network Layer Protection - improvements

edge-firewall/network-lists/index.md
=> Network Lists_EN_Fireawall_update

api/v3/network-lists/index.md
=> Network Lists - API V3_EN

load-balancer/2021-01-14-index.md
Sugestões de melhorias para a doc.
Hello, @VitorEltz-Azion! 
Vc poderia review está doc, please?
Thank you :)
=> PMK-477-Documentation-Load-Balancer_EN

edge-application/rules-engine/2021-01-14-index.md
Remoção cloud storage de acordo com sabrina e melhoras na doc
=> PMK-534-Rules-Engine-Edge-App-remove-cloud-storage_EN

edge-application/single-origin/2021-01-14-index.md
Melhora na documentação e remoção do cloud storage de acordo com Sabrina.
=> PMK-534-Remove-quotes-cloud-storage_SINGLE_ORIGIN_EN

edge-application/edge-functions-instances/2021-01-14-index.md
EN version revised.
Slight changes in the structure and some formatting adjustments.
=> PMK-464-Edge-Application-Edge-Functions-Instances_EN

first-steps/2021-01-14-index.md
=> Fix typo on first steps

image-processor/2021-01-14-index.md
doc improvements and corrections
=> PMK-550-Doc-Image-Processor_EN

edge-orchestrator/edge-node/2021-01-14-index.md
change in the credentials part and minor adjustments in the documentation.
=> PMK-626-Edge-Nodes-update_EN

edge-pulse/2021-01-14-index.md
=> PMK-478-Documentation-Edge-Pulse_EN

support/2021-01-14-index.md
improvements
@lucascazarotto and @rafaelsouza01, could you validate this doc, please? :)
Thank youuu!
=> PMK-530-Documentation-Products-Support_EN

edge-application/2021-01-14-index.md, edge-functions/2021-01-14-index.md, first-steps/2021-01-14-index.md
Signed-off-by: Alisson Marcelo <alisson.marcelo@azion.com>
=> Fix typos on first steps and edge products

accounts/delete-account/2021-05-03-index.md
Hello there!
@rafaelsouza01 and @Sabrinacmoreira 
Aqui esta a versão em EN da nova doc de deleção de contas. 
Have fun! :)
=> PMK-611-new-doc-account-deletion

accounts/Clients/2021-03-26-index.md
New doc- Feature Clients for Group type accounts (reseller)
English version.
Thanks!
=> PMK-388-Accounts-Clients_EN

real-time-metrics/2021-01-14-index.md
This PR substitutes PR#85 due to conflicts after intregrations with Forestry.
=> PMK-548-Real-time-metrics-EN

edge-functions/runtime-apis/javascript/fetch-event/2021-01-14-index.md
Slight changes to align with the PT version.
Question: line 33 - "(...) what will happen until the response:" this sentence is also awkward in Portugues, I'd like to understand. Thanks!
*Celeste has not tested this function.
=> PMK-465-JavaSRuntime-Apis--FetchEvent_EN

data-streaming/2021-01-14-index.md
included new endpoints Google BigQuery  and Elasticsearch.
=> PMK-717 e PMK-719-Data streaming connectors

data-streaming/2021-01-14-index.md
=> PMK-458-data-streaming-data-source_EN

data-streaming/2021-01-14-index.md
Slight adjustments in the Payload example.
=> PMK-730-data-streaming-adjustments

how-to/open-ticket/2021-01-14-index.md
Doc updated.
Marcus Both and Fernando Morassutti have already revised the PT_version via goolge docs.
Thanks!
=> PMK-641-how-to-Tickets

how-to/open-ticket/2021-01-14-index.md
=> PMK-641-tickets_corrections

accounts/users-and-teams/2021-01-14-index.md
Improvements required due  to recent questions to our Support team.
=> PMK-778-accountsEN updated

edge-functions/2021-01-14-index.md
Pessoal, segue o PR do webpack. Criei como um adendo à página de EF, somente em inglês para validarmos antes.
Deixei o nome seção "Edge Functions with multiple files" mesmo. Não sabia se o termo webpack deveria aparecer já no título.
=> PMK-832-ef-pack_EN

edge-functions/runtime-apis/javascript/web-standards/2021-01-14-index.md
=> PMK-465-JavaSRuntime-Apis-WebStandards_EN

real-time-events/2021-01-14-index.md
update: variables, filter by, etc
=> PMK-884-Real-Time-Events update

edge-functions/runtime-apis/javascript/request/2021-01-14-index.md
Slight corrections.
*Question: isn't there any observation to include in lines 73 and 75?
-event.type: string >> any note?
-event.request: request >> any note?
*Celeste hasn't tested this function.
=> PMK-465-JavaSRuntime-Apis-Request_EN

edge-functions/runtime-apis/javascript/response/2021-01-14-index.md
Edge Functions - JavaSRuntime -API - Response_EN
Slight changes.
=> PMK-465-JavaSRuntime-Apis-Response_EN

edge-application/real-time-purge/2021-01-14-index.md
=> PMK-768-Real-Time-Purge update_EN

integration-services/2021-01-14-index.md
O documento em EN não existia anteriormente.
=> PMK-777-Integration-services_EN (write version)

api/v3/intelligent-dns/2021-01-14-index.md
=> PMK-881-iDNS-API Weighted Policy_EN

data-streaming/2021-01-14-index.md
highlighted the use of ASCII encoding in DS.
=> PMK-967-DS-ASCII

data-streaming/2021-01-14-index.md
- new connector + slight adjustments.
=> PMK-1061-DS_aws-connector

edge-application/real-time-purge/2021-01-14-index.md
It would be nice if we could add some images to exemplify in a better way. Let me know what you think :)
=> PMK-1025-Real-Time Purge update_EN

first-steps/2021-01-14-index.md
=> PMK-1551- sign up documentation update_EN

edge-functions/2021-01-14-index.md
Pessoal, segue um draft. Tem dois comentários que deixei em itálico.
=> PMK-1144-Edge-Functions-Args-in-JS_EN

edge-functions/javascript-examples/2021-04-14-index.md, edge-functions/javascript-examples/using-args/2021-04-14-index.md
=> PMK-1175-js-ex-args_EN

changelog/2021-01-14-index.md
Change log  >> 1st draft - Still waiting for more updates.<<
=> PMK-1575-change-logAug

api/v2/2021-01-14-index.md
Updated rates.
@evandrometz and @julianoazion helped with data.
@HSantosAzion or @VitorEltz-Azion please approve. ;)
=> PMK-1442-V2ratelimit

api/v3/2021-01-14-index.md
Both and Morassutti already approved via slack.
=> PMK-1442-ratelimit

data-streaming/2021-01-14-index.md
=> PMK-1157-kafka

changelog/2021-01-14-index.md
=> PMK-1784-change-log-sept

api/v3/edge-firewall/2021-01-14-index.md, how-to/configurations/gzip-mime-types/2021-01-14-index.md
=> PMK-847-how-to-gzip-mime-types_EN

products/edge-application/domains/2021-01-14-index.md
Include the steps to delete a domain
=> Add the deletion process
